name: Reusable Quality Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.14"
      os:
        required: false
        type: string
        default: "ubuntu-22.04"

jobs:
  quality:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run checks
        run: make check
