name: Validate Package

on:
  workflow_call:
    inputs:
      python-version:
        description: "The version of Python to use"
        required: true
        type: string
      os:
        description: "The operating system to use"
        required: true
        type: string

jobs:
  Test:
    name: Testing Package
    uses: ./.github/workflows/tests_and_type_check.yml
    with:
      os: ${{ inputs.os }}

  Quality:
    name: Package Quality
    uses: ./.github/workflows/quality.yml
    with:
      python-version: ${{ inputs.python-version }}
      os: ${{ inputs.os }}

  Rust-Quality:
    name: Rust Quality
    uses: ./.github/workflows/rust_quality.yml
    with:
      os: ${{ inputs.os }}
